### ISSUE TITLE
Replace p wrapper by fieldset

### ISSUE THREAD

**Issue by wpmarmite** [abrudtkuhl/restrict-content-pro-require-terms#1]
Hello,

The terms checkbox is wrapped by a p tag. It should be a fieldset tag with a rcp_terms_fieldset class IMHO. What do you think ?

All the best
Alex

**Comment by abrudtkuhl** [comment]
I'm interested in seeing that - can you submit a PR with the update?

**Comment by wpmarmite** [comment]
Done

**Comment by abrudtkuhl** [comment]
Merged via PR and released to wp.org
