### ISSUE TITLE
Errors not being checked via ajax due to hook only loading if ! is_admin()

### ISSUE THREAD

**Issue by ashleyfae** [abrudtkuhl/restrict-content-pro-require-terms#3]
This snippet is causing error checks to not work in the ideal manner:

```php
   if ( ! is_admin() ) {
      add_action( 'rcp_after_register_form_fields', array( $this, 'terms_field' ) );
      add_action( 'rcp_form_errors', array( $this, 'check_for_agreement' ) );
    }
```

Because the `rcp_form_errors` action is only being added if `! is_admin()`, the error checks can't happen via ajax. The whole page actually reloads. It still fundamentally works - it just isn't as slick as it could be. :)

**Comment by abrudtkuhl** [comment]
Would love to see a Pull Request with a fix :)
