### ISSUE TITLE
Add support for privacy policy as well

### ISSUE THREAD

**Issue by ashleyfae** [abrudtkuhl/restrict-content-pro-require-terms#5]
Many people working on GDPR compliance are adding separate checkboxes for agreeing to terms and agreeing to a privacy policy. Are you open to adding a second field for agreeing to the privacy policy? If so, I'd be happy to work up a PR.

**Comment by abrudtkuhl** [comment]
Yea definitely if it's optional

Andy Brudtkuhl
youmetandy.com

**Comment by ashleyfae** [comment]
PR: #6
